import 'package:flutter/material.dart';
import 'package:greenly/assumptions.dart';
import 'package:greenly/components/base_layout.dart';
import 'package:greenly/pages/collection/commute_assumption.dart';
import 'package:greenly/pages/collection/food_assumption.dart';
import 'package:provider/provider.dart';

// Utility component for element spacing.
SizedBox _spacer({double? h}) => (SizedBox(height: h ?? 4.0));

/// This page allows the user to configure settings related to the use and feal of the app.
/// It also allows to better tune the assumptions regarding emissions, generated by the user.

class SettingsPage extends StatelessWidget {
  const SettingsPage({super.key});

  @override
  Widget build(BuildContext context) {
    var textTheme = TextTheme.of(context);

    const scrollViewEdgeInsets = EdgeInsets.symmetric(
      horizontal: 12,
      vertical: 12,
    );

    return BasePageLayout(
      floatingBtnIcon: Icons.add,
      floatingBtnTooltip: 'Available Actions',
      // --- Layout
      body: DefaultTabController(
        length: 3,
        child: Column(
          children: [
            // --- Header
            TabBar(
              tabs: <Widget>[
                Tab(icon: Icon(Icons.settings_outlined)),
                Tab(icon: Icon(Icons.candlestick_chart_outlined)),
                Tab(icon: Icon(Icons.person_outlined)),
              ],
            ),
            // --- Body
            Expanded(
              child: Padding(
                padding: scrollViewEdgeInsets,
                child: TabBarView(
                  children: [
                    // --- Gamification and Notifications
                    _baseSettingsSection(textTheme),

                    // --- GHG emission assumption settings
                    _baseAssumptionsSection(context, textTheme),

                    // --- User profile settings
                    SingleChildScrollView(child: const Text('Super Text')),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
      hasActionButton: false,
    );
  }

  // --- GHG emission assumption settings
  SingleChildScrollView _baseAssumptionsSection(
    BuildContext context,
    TextTheme textTheme,
  ) {
    return SingleChildScrollView(
      padding: EdgeInsets.symmetric(horizontal: 10),
      // --- Body
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        spacing: 6,
        children: [
          // --- Heading & tittles
          Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisAlignment: MainAxisAlignment.start,
            spacing: 4,
            children: [
              Text('Base Assumptions', style: textTheme.titleMedium),
              Text(
                'The base values of your day-to-day.',
                style: textTheme.bodyMedium,
              ),
            ],
          ),
          _spacer(),
          Divider(height: 2, color: Colors.grey.shade300),
          _spacer(),
          // --- Commute assumption header
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            spacing: 4,
            children: [
              Text('Commute', style: textTheme.titleSmall),
              // --- Add new Assumption -> redirects to data collection page.
              TextButton(
                onPressed: () {
                  Navigator.of(context).push(
                    MaterialPageRoute(
                      builder: (context) => NewCommuteAssumption(),
                    ),
                  );
                },
                style: TextButton.styleFrom(
                  backgroundColor: Colors.grey.shade200,
                  padding: EdgeInsets.symmetric(horizontal: 12),
                  foregroundColor: Colors.blueGrey,
                ),
                child: Text('New Entrie'),
              ),
            ],
          ),
          _spacer(),
          // --- Use the assumptions notifier to get updates on data change.
          // --- This consumer is for Transport assumptions only.
          Consumer<AssumptionsModel>(
            builder:
                (
                  BuildContext context,
                  AssumptionsModel assumptions,
                  Widget? child,
                ) {
                  var children = assumptions
                      .getAssumptionsPerType<TransportAssumption>();

                  var transportAssumptions = List<Widget>.generate(
                    children.length,
                    (int index) {
                      final child = children[index];
                      return child.toWidget();
                    },
                  );

                  return Column(
                    mainAxisSize: MainAxisSize.max,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      children.isEmpty
                          ? Column(
                              children: [
                                Text(
                                  'No entries here!',
                                  style: TextStyle(
                                    color: Colors.grey.shade500,
                                    fontStyle: FontStyle.italic,
                                  ),
                                ),
                              ],
                            )
                          : SizedBox(),
                      Column(children: transportAssumptions),
                    ],
                  );
                },
          ),
          _spacer(),
          Divider(height: 2, color: Colors.grey.shade300),
          _spacer(h: 20),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            spacing: 4,
            children: [
              Text('Food', style: textTheme.titleSmall),
              // --- Add new Assumption -> redirects to data collection page.
              TextButton(
                onPressed: () {
                  Navigator.of(context).push(
                    MaterialPageRoute(
                      builder: (context) => NewFoodAssumption(),
                    ),
                  );
                },
                style: TextButton.styleFrom(
                  backgroundColor: Colors.grey.shade200,
                  padding: EdgeInsets.symmetric(horizontal: 12),
                  foregroundColor: Colors.blueGrey,
                ),
                child: Text('New Entrie'),
              ),
            ],
          ),
          _spacer(),
          // --- Use the assumptions notifier to get updates on data change.
          // --- This consumer is for Food assumptions only.
          Consumer<AssumptionsModel>(
            builder:
                (
                  BuildContext context,
                  AssumptionsModel assumptions,
                  Widget? child,
                ) {
                  var children = assumptions
                      .getAssumptionsPerType<FoodAssumption>();

                  var foodAssumptions = List<Widget>.generate(children.length, (
                    int index,
                  ) {
                    var child = children[index];
                    return child.toWidget();
                  });

                  return Column(
                    mainAxisSize: MainAxisSize.max,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      children.isEmpty
                          ? Column(
                              children: [
                                Text(
                                  'No entries here!',
                                  style: TextStyle(
                                    color: Colors.grey.shade500,
                                    fontStyle: FontStyle.italic,
                                  ),
                                ),
                              ],
                            )
                          : SizedBox(),
                      Column(children: foodAssumptions),
                    ],
                  );
                },
          ),
        ],
      ),
    );
  }

  SingleChildScrollView _baseSettingsSection(TextTheme textTheme) {
    return SingleChildScrollView(
      padding: EdgeInsets.symmetric(horizontal: 10),
      child: Column(
        spacing: 6,
        children: [
          Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisAlignment: MainAxisAlignment.start,
            spacing: 4,
            children: [
              Text('Base Settings', style: textTheme.titleMedium),
              Text(
                'Notifications and functionality.',
                style: textTheme.bodyMedium,
              ),
            ],
          ),
          Container(),
          Column(
            mainAxisSize: MainAxisSize.max,
            children: [
              ToggleOption(
                optionIcon: Icons.notifications_rounded,
                active: true,
                title: 'Receive Notifications',
                description: 'Set to OFF sends only essential notifications.',
              ),
              ToggleOption(
                optionIcon: Icons.calendar_month_rounded,
                active: false,
                title: 'Reminders',
                description: 'Helps you achieve your goals.',
              ),
              ToggleOption(
                optionIcon: Icons.gamepad_rounded,
                active: true,
                action: (bool newValue) {},
                title: 'Ai Gamification',
                description: 'Gamify your tasks, and progress tracking.',
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class ToggleOption extends StatelessWidget {
  final IconData optionIcon;
  final bool active;
  final String title;
  final String? description;
  final void Function(bool)? action;

  const ToggleOption({
    required this.optionIcon,
    required this.active,
    required this.title,
    super.key,
    this.description,
    this.action,
  });

  @override
  Widget build(BuildContext context) {
    var textTheme = TextTheme.of(context);

    var cardShape = RoundedRectangleBorder(
      side: BorderSide(
        color: Colors.grey.shade100,
        width: 0,
        style: BorderStyle.solid,
      ),
      borderRadius: BorderRadius.all(Radius.circular(12)),
    );

    return Card(
      shape: cardShape,
      color: Colors.white,
      elevation: 1,
      child: Padding(
        padding: EdgeInsetsGeometry.all(18),
        child: Row(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          spacing: 10,
          children: [
            Icon(optionIcon, size: 28),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                  Text(title, style: textTheme.titleSmall),
                  description != null
                      ? Text(description!, style: textTheme.bodySmall)
                      : Container(),
                ],
              ),
            ),
            Switch(value: active, onChanged: action),
          ],
        ),
      ),
    );
  }
}
